name: Create and publish a Podman image

on:
  schedule:
    - cron: "30 16 * * *"
  push:
    branches: ['main']
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: registry.fedoraproject.org/fedora-minimal:latest
          image: ghcr.io/vietchinh/lxd-in-podman:latest
      - name: Extract metadata (tags, labels) for Docker
        if: steps.check.outputs.needs-updating == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest=true
      - name: Build Image
        if: steps.check.outputs.needs-updating == 'true'
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: ./Containerfile
          image: ${{ github.repository }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          oci: false
          layers: true
      - name: Push To GHCR
        if: steps.check.outputs.needs-updating == 'true'
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
          extra-args: |
            --disable-content-trust